install npm

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,11 +33,17 @@ jobs:
           cache: "pnpm"
           registry-url: "https://registry.npmjs.org"
 
+      - name: Upgrade npm for trusted publishing
+        run: npm install -g npm@latest
+
       - name: Install dependencies
         run: pnpm run build-install
 
       - name: Build Packages
         run: pnpm run build
+
+      - name: Check npm OIDC auth
+        run: npm whoami || (echo "whoami failed" && exit 1)
 
       - name: Create Release Pull Request or Publish to npm
         id: changesets
@@ -50,7 +56,6 @@ jobs:
           title: "[ci] release"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
 
       - uses: actions/github-script@v7
         if: steps.changesets.outputs.published == 'true'
